import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">FrameSix</Link>
        </li>
        <li>
          <Link to="/frameone">FrameOne</Link>
        </li>
        <li>
          <Link to="/framefour">FrameFour</Link>
        </li>
        <li>
          <Link to="/framefive">FrameFive</Link>
        </li>
        <li>
          <Link to="/frameseven">FrameSeven</Link>
        </li>
        <li>
          <Link to="/frameeight">FrameEight</Link>
        </li>
        <li>
          <Link to="/framenine">FrameNine</Link>
        </li>
        <li>
          <Link to="/frameten">FrameTen</Link>
        </li>
        <li>
          <Link to="/frameeleven">FrameEleven</Link>
        </li>
        <li>
          <Link to="/frametwelve">FrameTwelve</Link>
        </li>
        <li>
          <Link to="/framethirteen">FrameThirteen</Link>
        </li>
        <li>
          <Link to="/framefourteen">FrameFourteen</Link>
        </li>
        <li>
          <Link to="/framefifteen">FrameFifteen</Link>
        </li>
        <li>
          <Link to="/framesixteen">FrameSixteen</Link>
        </li>
        <li>
          <Link to="/frameseventeen">FrameSeventeen</Link>
        </li>
        <li>
          <Link to="/frameeighteen">FrameEighteen</Link>
        </li>
        <li>
          <Link to="/framenineteen">FrameNineteen</Link>
        </li>
        <li>
          <Link to="/frametwenty">FrameTwenty</Link>
        </li>
        <li>
          <Link to="/frametwentyone">FrameTwentyOne</Link>
        </li>
        <li>
          <Link to="/frametwentytwo">FrameTwentyTwo</Link>
        </li>
        <li>
          <Link to="/frametwentythree">FrameTwentyThree</Link>
        </li>
        <li>
          <Link to="/frametwentyfour">FrameTwentyFour</Link>
        </li>
        <li>
          <Link to="/frametwentynine">FrameTwentyNine</Link>
        </li>
        <li>
          <Link to="/framethirty">FrameThirty</Link>
        </li>
        <li>
          <Link to="/framethirtyone">FrameThirtyOne</Link>
        </li>
        <li>
          <Link to="/framethirtytwo">FrameThirtyTwo</Link>
        </li>
        <li>
          <Link to="/framethirtyfour">FrameThirtyFour</Link>
        </li>
        <li>
          <Link to="/framethirtyfive">FrameThirtyFive</Link>
        </li>
        <li>
          <Link to="/framethirtythree">FrameThirtyThree</Link>
        </li>
        <li>
          <Link to="/framethirtysix">FrameThirtySix</Link>
        </li>
        <li>
          <Link to="/framethirtyseven">FrameThirtySeven</Link>
        </li>
        <li>
          <Link to="/framethirtyeight">FrameThirtyEight</Link>
        </li>
        <li>
          <Link to="/framethirtynine">FrameThirtyNine</Link>
        </li>
        <li>
          <Link to="/frameforty">FrameForty</Link>
        </li>
        <li>
          <Link to="/framefortyone">FrameFortyOne</Link>
        </li>
        <li>
          <Link to="/framefortyfour">FrameFortyFour</Link>
        </li>
        <li>
          <Link to="/framefortyfive">FrameFortyFive</Link>
        </li>
        <li>
          <Link to="/framefortysix">FrameFortySix</Link>
        </li>
        <li>
          <Link to="/framefortyseven">FrameFortySeven</Link>
        </li>
        <li>
          <Link to="/framefortyeight">FrameFortyEight</Link>
        </li>
        <li>
          <Link to="/framefortynine">FrameFortyNine</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
